### ISSUE TITLE
Use of not established terminology

### ISSUE THREAD

**Issue by loewenstein** [open-component-model/ocm-spec#35]
I have asked myself what a software-bill-of-deliveries (SBOD) could be and was surprised that also Google can't give an answer to this.

https://github.com/open-component-model/ocm-spec/blob/4f2691203f6ac4d20c8841ccc693b8ab6122c45a/README.md?plain=1#L5

I would propose that we should not introduce such terms lightly and I also feel the [paragraph differencing SBOM and OCM](https://github.com/open-component-model/ocm-spec#comparison-with-software-bill-of-materials) is a bit shallow. In particular, there is a lack of reasoning why the same results couldn't be achieved by integrating into a rather well established standard like CyclonDX or SPDX.

**Comment by In-Ko** [comment]
We have not introduced the term "lightly", but definitely _on purpose_, to clearly show that the OCM is not a SBoM, which are focusing on all the details like all libraries contained in a certain software package. This focus of SBoMs is of course a totally valid approach and much needed (just look at openssf), but it is simply not the one OCM takes and aims for: OCM only looks at the bigger parts (like docker images), which need to be _delivered_ and subsequently also deployed. That is why we introduce the term SBoD.
The problem with the well-established standards is that both seem to be getting more and more "generic", the more usecases are being covered, making it in some cases problematic to interpret the documents based on one of those standards in the right way, without applying specific semantics. One always seems to require a specific interpretation, depending on the usecase, in order to make use of SPoM documents. This again is a valid approach, but in the OCM team, we had the strong feeling that the usecase OCM tries to cover is not an _additional_ one for SPDX or CycloneDX, but a rather _different_ one, focusing on a different level of artifacts.

**Comment by jensh007** [comment]
Closing this as there were no additional comments by author for a long time.
