### ISSUE TITLE
Feedback for ocm-spec restructuring 

### ISSUE THREAD

**Issue by morri-son** [open-component-model/ocm-spec#79]
Hi @Jens, hear a first version of feedback. And yes, I didn't find time to really come to the meat of the changes...I'll hop onto that after the vacation period...

- overview: the part that differentiates ocm and its SBOD/xBOM/dBOM character from an SBOM has been removed. Should we bring this back?
- section "Model"
  - only sources and resources are mentioned, should we mention labels with regards to offering a beneficial possibility to store any kind of metadata on all layers of an OCM component?
  - sources are mentioned as artifacts same as resources. Are they really artifacts or would it make more sense to just call the sources, specifying the origin (code source) of the resources? Hmmm...just reading on and artifact here in this sense are more the artifacts of an OCM version (and indeed whatever is put into an ocm version is persisted as blob). But at least reading "artifact" I don't relate this more with a resource specified in an ocm version, but...

**Comment by jensh007** [comment]
Regarding this overview I removed this, because it should not be part of the spec. It should however preserved. I suggest to move this to the website. I also would recommend to review this section and rewrite it partially.

The definition of sources as artifacts is the same as in the current version of the spec (at least I did not intend to change this).
